services:
    kassoulet.ThreesixtyLearningearning.utils:
        class: Kassoulet\ThreesixtyLearningBundle\Services\ThreesixtyLearningService
        calls:  
            - [ 'setApi', ['@kassoulet.ThreesixtyLearning.api'] ]